#!/bin/sh

/usr/bin/invoke_app -t stiritup \
                    -C "start_jupyter -A -t -T @tool main.ipynb" \
                    -u anaconda-7 \
                    -r none \
                    -w headless
